CXX=g++
CXXFLAGS= -g -Wall
ROOTLIBS=`root-config --libs`
ROOTINC=`root-config --cflags`

BINDIR=bin
OBJDIR=obj
SRCDIR=src
INCDIR=include

OBJECTS  = $(OBJDIR)/AtlasStyle.o $(OBJDIR)/AtlasUtils.o $(OBJDIR)/MbTools.o $(OBJDIR)/MbStyle.o $(OBJDIR)/MbConstants.o
PROGRAMSOBJ = $(OBJDIR)/PlotGapDistCorr.o  $(OBJDIR)/PlotGapDistRaw.o $(OBJDIR)/PlotGapDistCorrSys.o 
PROGRAMS = $(BINDIR)/PlotGapDistCorr $(BINDIR)/PlotGapDistCorrSys $(BINDIR)/PlotGapDistRaw

DEFINE=
ifeq ("$(USER)", "pruzicka") 
   DEFINE=-DRUZICKA
endif 
ifeq ("$(USER)", "olda") 
	DEFINE=-DKEPKA
endif 
ifeq ("$(USER)", "tam") 
	DEFINE=-DMARTIN
endif   


all:$(OBJECTS) $(PROGRAMS) $(PROGRAMSOBJ)

$(BINDIR)/PlotGapDistRaw:$(OBJDIR)/PlotGapDistRaw.o $(OBJECTS) 
	$(CXX) -o $@ $^ $(ROOTLIBS)

$(BINDIR)/PlotGapDistCorr:$(OBJDIR)/PlotGapDistCorr.o $(OBJECTS) 
	$(CXX) -o $@ $^ $(ROOTLIBS)

$(BINDIR)/PlotGapDistCorrSys:$(OBJDIR)/PlotGapDistCorrSys.o $(OBJECTS) 
	$(CXX) -o $@ $^ $(ROOTLIBS)

$(OBJDIR)/PlotGapDistCorrSys.o:$(SRCDIR)/PlotGapDistCorrSys.cxx
	$(CXX) -c $(CXXFLAGS) $< -o $@ -I$(INCDIR) $(ROOTINC)

$(OBJDIR)/PlotGapDistCorr.o:$(SRCDIR)/PlotGapDistCorr.cxx
	$(CXX) -c $(CXXFLAGS) $< -o $@ -I$(INCDIR) $(ROOTINC)

$(OBJDIR)/PlotGapDistRaw.o:$(SRCDIR)/PlotGapDistRaw.cxx
	$(CXX) -c $(CXXFLAGS) $< -o $@ -I$(INCDIR) $(ROOTINC)

$(OBJDIR)/AtlasStyle.o:$(SRCDIR)/AtlasStyle.cxx $(INCDIR)/AtlasStyle.h
	$(CXX) -c $(CXXFLAGS) $< -o $@ $(ROOTINC) -I$(INCDIR)/

$(OBJDIR)/AtlasUtils.o:$(SRCDIR)/AtlasUtils.cxx $(INCDIR)/AtlasUtils.h
	$(CXX) -c $(CXXFLAGS) $< -o $@ $(ROOTINC) -I$(INCDIR)/

$(OBJDIR)/MbStyle.o:$(SRCDIR)/MbStyle.cxx $(INCDIR)/MbStyle.h
	$(CXX) -c $(CXXFLAGS) $< -o $@ $(ROOTINC) -I$(INCDIR)/

$(OBJDIR)/MbTools.o:$(SRCDIR)/MbTools.cxx $(INCDIR)/MbTools.h 
	$(CXX) -c $(CXXFLAGS) $< -o $@ $(ROOTINC) -I$(INCDIR)/

$(OBJDIR)/MbConstants.o:$(SRCDIR)/MbConstants.cxx $(INCDIR)/MbConstants.h
	$(CXX) -c $(CXXFLAGS) $< -o $@ $(ROOTINC) -I$(INCDIR)/


clean: 
	rm -vf  $(OBJECTS) $(PROGRAMS)
